/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import AboutMe from './tokens/AboutMe'
import Gmail from './tokens/Gmail'
import Phone from './tokens/Phone'
import OpenAI from './tokens/OpenAI'
import Vanderbilt from './tokens/Vanderbilt'
import ThreeD from './tokens/ThreeD'
import DigitalArt from './tokens/DigitalArt'
import Linktree from './tokens/Linktree'
import Github from './tokens/Github'
import LinkedIn from './tokens/LinkedIn'


export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/XRVTldnmQ61eDtR3/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#000000']} />
      <AboutMe/>
      <Gmail/>
      <Phone/>
      <OpenAI/>
      <Vanderbilt/>
      <ThreeD/>
      <DigitalArt/>
      <Linktree/>
      <Github/>
      <LinkedIn/>

      <group {...props} dispose={null}>
      
      <group name="davidwaldherr.com" position={[200, -1300, 54.5]}>
          <mesh
            name="d"
            geometry={nodes.d.geometry}
            material={materials['My Text Material']}
            position={[-897, 16.5, 0]}
          />
          <mesh
            name="a"
            geometry={nodes.a.geometry}
            material={materials['My Text Material']}
            position={[-812, 16.5, 0]}
          />
          <mesh
            name="v"
            geometry={nodes.v.geometry}
            material={materials['My Text Material']}
            position={[-727, 16.5, 0]}
          />
          <mesh
            name="i"
            geometry={nodes.i.geometry}
            material={materials['My Text Material']}
            position={[-642, 16.5, 0]}
          />
          <mesh
            name="i"
            geometry={nodes.i1.geometry}
            material={materials['My Text Material']}
            position={[-642, 16.5, 0]}
          />
          <mesh
            name="d"
            geometry={nodes.d1.geometry}
            material={materials['My Text Material']}
            position={[-557, 16.5, 0]}
          />
          <mesh
            name="w"
            geometry={nodes.w.geometry}
            material={materials['My Text Material']}
            position={[-472, 16.5, 0]}
          />
          <mesh
            name="a"
            geometry={nodes.a1.geometry}
            material={materials['My Text Material']}
            position={[-387, 16.5, 0]}
          />
          <mesh
            name="l"
            geometry={nodes.l.geometry}
            material={materials['My Text Material']}
            position={[-302, 16.5, 0]}
          />
          <mesh
            name="d"
            geometry={nodes.d2.geometry}
            material={materials['My Text Material']}
            position={[-217, 16.5, 0]}
          />
          <mesh
            name="h"
            geometry={nodes.h.geometry}
            material={materials['My Text Material']}
            position={[-132, 16.5, 0]}
          />
          <mesh
            name="e"
            geometry={nodes.e.geometry}
            material={materials['My Text Material']}
            position={[-47, 16.5, 0]}
          />
          <mesh
            name="r"
            geometry={nodes.r.geometry}
            material={materials['My Text Material']}
            position={[38, 16.5, 0]}
          />
          <mesh
            name="r"
            geometry={nodes.r1.geometry}
            material={materials['My Text Material']}
            position={[123, 16.5, 0]}
          />
          <mesh
            name="."
            geometry={nodes['.'].geometry}
            material={materials['My Text Material']}
            position={[208, 16.5, 0]}
          />
          <mesh
            name="c"
            geometry={nodes.c.geometry}
            material={materials['My Text Material']}
            position={[293, 16.5, 0]}
          />
          <mesh
            name="o"
            geometry={nodes.o.geometry}
            material={materials['My Text Material']}
            position={[378, 16.5, 0]}
          />
          <mesh
            name="m"
            geometry={nodes.m.geometry}
            material={materials['My Text Material']}
            position={[463, 16.5, 0]}
          />
        </group>

        <OrthographicCamera
          name="Camera"
          makeDefault={true}
          zoom={0.36}
          far={100000}
          near={-100000}
          position={[-47.43, 343.44, 8457.66]}
        />
        <pointLight
          name="Point Light"
          castShadow
          intensity={1}
          distance={2000}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={100}
          shadow-camera-far={100000}
          position={[0, 0, 7281.89]}
        />
        
        <group name="Top Token" position={[-50, 1100, 0]} scale={2.6}>
          <mesh
            name="Ring"
            geometry={nodes.Ring.geometry}
            material={materials.Gold}
            position={[-0.15, -5.24, -22.5]}
            scale={0.38}
          />
        </group>
        <group name="Home Token" position={[-1611.93, 1153.56, 5.42]} scale={0.78}>
          <mesh
            name="Shape 23"
            geometry={nodes['Shape 23'].geometry}
            material={materials.Gold}
            castShadow
            receiveShadow
            position={[-131.74, 22.89, 7.63]}
            scale={0.76}
          />
          <mesh
            name="Shape4"
            geometry={nodes.Shape4.geometry}
            material={materials.Gold}
            castShadow
            receiveShadow
            position={[-95.15, 17.49, 6.4]}
            scale={0.76}
          />
          <mesh
            name="Merged Geometry 3"
            geometry={nodes['Merged Geometry 3'].geometry}
            material={materials.Gold}
            castShadow
            receiveShadow
          />
          <mesh
            name="Ellipse 32"
            geometry={nodes['Ellipse 32'].geometry}
            material={materials['Ellipse 32 Material']}
            castShadow
            receiveShadow
            position={[0.13, 1.57, -18.97]}
          />
        </group>
        
        
        
        
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" position={[0, 1, 0]} />
      </group>
    </>
  )
}
